api_platform:
  defaults:
    pagination_enabled: true
    pagination_items_per_page: 15
    pagination_maximum_items_per_page: 100
    pagination_client_enabled: true
    pagination_client_items_per_page: true
    pagination_client_partial: true
  title: BTPConnect API
  version: 1.0.0
  formats:
    json: ["application/json"]
    jsonld: ["application/ld+json"]
    html: ["text/html"]
    jsonopenapi: ["application/vnd.openapi+json"]
    multipart: ["multipart/form-data"]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  mapping:
    paths:
      - "%kernel.project_dir%/src/Entity"
      - "%kernel.project_dir%/src/ApiResource"
      - "%kernel.project_dir%/src/Dto"
