nelmio_cors:
  defaults:
    origin_regex: false
    allow_origin: [
        "%env(CORS_ALLOW_ORIGIN)%",
        "http://localhost:3000",
        "https://www.btpconnets.com",
        "https://btpconnets.com",
      ] # ['*'] '%env(CORS_ALLOW_ORIGIN)%'
    allow_methods:
      ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
    expose_headers: ["Link", "X-Total-Count"]
    max_age: 3600
    allow_credentials: true # Activer les cookies et informations d'authentification
  paths:
    "^/api/":
      ~
      # origin_regex: false
      # allow_origin: ['*']
      # allow_headers: ['*']
      # allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
      # max_age: 3600
    "^/": ~
